version: '3.3'

services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.8.2
    restart: always
    ports:
      - 8181:8181
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - evolution-net
    env_file:
      - ./Docker/.env
    command: ['node', './dist/src/main.js']
    expose:
      - 8181

volumes:
  evolution_instances:
  evolution_store:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
